# Generated by Django 5.1.1 on 2024-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('mobile', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
