# Generated by Django 5.1 on 2024-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
