# Generated by Django 5.1 on 2024-10-27 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('US 7', 'US 7'), ('US 8', 'US 8'), ('US 9', 'US 9'), ('US 10', 'US 10'), ('EU 40', 'EU 40'), ('EU 42', 'EU 42')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('running', 'Running'), ('casual', 'Casual'), ('formal', 'Formal'), ('sports', 'Sports')], max_length=50)),
                ('pimage', models.ImageField(upload_to='shoes/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user')),
            ],
        ),
    ]
