# Generated by Django 5.1 on 2024-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_remove_product_color_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Reebok', 'Reebok')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Running', 'Running'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Sports', 'Sports'), ('Sneakers', 'Sneakers')], max_length=50),
        ),
    ]
