# Generated by Django 5.1 on 2024-11-21 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0009_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 9, 41, 22, 259747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 9, 41, 22, 258748, tzinfo=datetime.timezone.utc)),
        ),
    ]
