# Generated by Django 5.1 on 2024-12-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0016_remove_cart_qty_cartitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
