# Generated by Django 5.1 on 2024-12-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0018_alter_cartitem_product_alter_cartitem_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
