# Generated by Django 5.1 on 2024-12-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0020_alter_user_mobile_billing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('check', 'Check Payment'), ('gpay', 'Google Pay'), ('card', 'Credit/Debit Card')], default='gpay', max_length=50),
        ),
    ]
