# Generated by Django 5.1 on 2024-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0021_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('check', 'Check Payment'), ('gpay', 'Google Pay'), ('cod', 'Cash On Delivery'), ('card', 'Credit/Debit Card')], default='cod', max_length=50),
        ),
    ]
