# Generated by Django 5.1 on 2024-12-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0022_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='postal_code',
            new_name='zipcode',
        ),
    ]
