# Generated by Django 5.1 on 2024-12-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0024_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
