# Generated by Django 5.1 on 2024-12-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0025_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
