# Generated by Django 5.1 on 2024-12-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0026_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', editable=False, max_length=20),
        ),
    ]
