# Generated by Django 5.1 on 2024-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0027_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=20),
        ),
    ]
