# Generated by Django 5.1 on 2024-12-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0028_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipping', 'Shipping'), ('Ordered', 'Ordered'), ('Paid', 'Paid'), ('Saved', 'Saved')], default='Saved', max_length=20),
        ),
    ]
